# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/jeonghyejin/gbc/ASD

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/jeonghyejin/gbc

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jeonghyejin/gbc/CMakeFiles /home/jeonghyejin/gbc/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jeonghyejin/gbc/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named sayHello

# Build rule for target.
sayHello: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sayHello
.PHONY : sayHello

# fast build rule for target.
sayHello/fast:
	$(MAKE) -f greet/CMakeFiles/sayHello.dir/build.make greet/CMakeFiles/sayHello.dir/build
.PHONY : sayHello/fast

#=============================================================================
# Target rules for targets named greet

# Build rule for target.
greet: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 greet
.PHONY : greet

# fast build rule for target.
greet/fast:
	$(MAKE) -f greet/CMakeFiles/greet.dir/build.make greet/CMakeFiles/greet.dir/build
.PHONY : greet/fast

#=============================================================================
# Target rules for targets named sayBye

# Build rule for target.
sayBye: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sayBye
.PHONY : sayBye

# fast build rule for target.
sayBye/fast:
	$(MAKE) -f bye/CMakeFiles/sayBye.dir/build.make bye/CMakeFiles/sayBye.dir/build
.PHONY : sayBye/fast

#=============================================================================
# Target rules for targets named bye

# Build rule for target.
bye: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bye
.PHONY : bye

# fast build rule for target.
bye/fast:
	$(MAKE) -f bye/CMakeFiles/bye.dir/build.make bye/CMakeFiles/bye.dir/build
.PHONY : bye/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... sayHello"
	@echo "... greet"
	@echo "... sayBye"
	@echo "... bye"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

